services:
  - type: web
    name: transaction-fraud-api
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
